[theme]
# App ka base theme (dark ya light)
base = "dark"

# Mukhya (primary) color (jaise buttons ka color)
primaryColor = "#00FF7F"  # Yeh ek accha sa Spring Green color hai

# Background ka color
backgroundColor = "#121212"

# Secondary background color (jaise sidebar)
secondaryBackgroundColor = "#282828"

# Text ka color
textColor = "#FFFFFF"

# Font
font = "sans serif"
